module.exports = {
  auth: require("./get/auth"),
  bookmark: require("./get/bookmark"),
  codi: require("./get/codi"),
  home: require("./get/home"),
  map: require("./get/map"),
  mypage: require("./get/mypage"),
  login: require("./post/login"),
  signout: require("./post/signout"),
  signup: require("./post/signup"),
  password: require("./put/password"),
  userinfo: require("./put/userinfo"),
  userphoto: require("./put/userphoto"),  
  deletepost: require("./del/deletepost"),
  removeuser: require("./del/removeuser"),  
}  