module.exports = {
    auth: require("./get/auth"),
    bookmark: require("./post/bookmark"),
    codi: require("./get/codi"),
    mypage: require("./get/mypage"),
    mypost: require("./get/mypost"),
    readpost: require("./get/readpost"),
    bookmarklist: require("./post/bookmarklist"),
    home: require("./post/home"),
    map: require("./post/map"),
    login: require("./post/login"),
    signout: require("./post/signout"),
    post: require("./post/write"),
    password: require("./put/password"),
    edituserinfo: require("./put/edituserinfo"),
    userphoto: require("./put/userphoto"),
    editpost: require("./put/editpost"),
    deletepost: require("./del/deletepost"),
    removeuser: require("./del/removeuser"),
    sociallogin: require("./post/sociallogin"),
    ////////
    map2: require("./post/map2"),
    usersController: require("./users"),
    postsController: require("./post"),
    chatsController: require("./chat"),
}
