module.exports = {
    auth: require("./get/auth"),
    bookmark: require("./post/bookmark"),
    codi: require("./get/codi"),
    mypage: require("./get/mypage"),
    mypost: require("./get/mypost"),
    readpost: require("./get/readpost"),
    bookmarklist: require("./get/bookmarklist"),
    home: require("./post/home"),
    map: require("./post/map"),
    login: require("./post/login"),
    signout: require("./post/signout"),
    post: require("./post/write"),
    password: require("./put/password"),
    userinfo: require("./put/userinfo"),
    userphoto: require("./put/userphoto"),
    editpost: require("./put/editpost"),
    deletepost: require("./del/deletepost"),
    removeuser: require("./del/removeuser"),
    sociallogin: require("./post/sociallogin"),
    usersController: require("./users"),
    postsController: require("./post"),
    chatsController: require("./chat"),
}
